package com.example.backEndProject.model;

public enum Interests {
    SOFTWARE_ENGINEERING,
    MACHINE_LEARNING,
    AI,
    ROBOTICS,
    FULL_STACK_DEVELOPMENT,
    BACK_END_DEVELOPMENT,
    FRONT_END_DEVELOPMENT,
    BUSINESS_DEVELOPMENT,
    ENTREPRENEURSHIP,
    ART,
    LITERATURE,
    LOCAL_EVENTS,
    INVESTING,
    STARTING_A_BUSINESS,
    WOMEN_IN_TECH,
    BAME_IN_TECH,
    VETERANS_IN_TECH,
    BANKING_AND_FINANCE,
    MEDITATION_AND_SPIRITUALITY,
    PHOTOGRAPHY,

}
